#include "screens.h"
#include "../theme.h"
#include "../components/container.h"
#include "../components/components.h"
#include "../components/input_field_component.h"
#include "../app_state.h"
#include "ui_constants.h"
#include <cctype>
#include <ftxui/component/app.hpp>
#include <ftxui/component/component.hpp>
#include <ftxui/component/component_base.hpp>
#include <ftxui/component/component_options.hpp>
#include <ftxui/component/event.hpp>
#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/color.hpp>
#include <ftxui/screen/terminal.hpp>
#include <string_view>


using namespace ftxui;

namespace theme = ui::theme;
namespace state = ui::state;
namespace constants = ui::screens::constants;

namespace{

// levenshtein distance formula to determine how similar two strings are
// generated by Gemini
auto levenshtein(std::string_view s1, std::string_view s2) -> int{
    const size_t s1_length = s1.size();
    const size_t s2_length = s2.size();

    // Use a single vector to track distances (current row)
    std::vector<int> distances(s2_length + 1);
    std::iota(distances.begin(), distances.end(), 0); 

    for (size_t i = 1; i <= s1_length; ++i) {
        int upper_left = distances[0]; // The "diagonal" value
        distances[0] = static_cast<int>(i); // Update the first column

        for (size_t j = 1; j <= s2_length; ++j) {
            int prev_upper_left = upper_left;
            upper_left = distances[j]; // Save for the next iteration's diagonal

            if (s1[i - 1] == s2[j - 1]) {
                distances[j] = prev_upper_left; // Characters match, no cost
            } else {
                // Take the minimum of (Insertion, Deletion, Substitution) + 1
                distances[j] = 1 + std::min({distances[j], distances[j - 1], prev_upper_left});
            }
        }
    }
    return distances[s2_length];
}


auto render_body(state::AppState& app_state) -> Component
{
  using namespace ui::components;

  Filter search_filter{filter_combiner(newline_input_filter, char_limit_input_filter(&app_state.search.search_field, constants::MAX_INPUT_CHARACTERS))};
  Component search_field{create_input_field(&app_state.search.search_field, "Search...", search_filter)};

  MenuOption option;

  option.on_enter = [&]{
    app_state.selected_screen = ui::state::SelectedScreen::MainVault;
  };

  auto menu{Menu(&app_state.main_vault.sites, &app_state.main_vault.entry_selected, option) | color(theme::FONT_COLOR)};
  
  auto layout{ Container::Vertical({
    search_field,
    menu,
  })};
  
  return Renderer(layout, [=, &app_state]{
    return hbox({
      separatorEmpty() | xflex,

      vbox({
        separatorEmpty() | size(ftxui::HEIGHT, ftxui::EQUAL, 4),
        search_field->Render(),
        separatorEmpty(),

        menu->Render() | vscroll_indicator | frame | yflex | borderLight,

        separatorEmpty() | size(ftxui::HEIGHT, ftxui::EQUAL, 4),
      }) | flex | size(ftxui::WIDTH, EQUAL, constants::MAX_INPUT_WIDTH),
      separatorEmpty() | xflex
    }) | flex;
  });
}

  
}// unnamed namespace


auto ui::screens::render_search_screen(state::AppState& app_state) -> Component
{
  Component header { components::render_header("SEARCH") };
  Component footer{ components::render_footer("EDITING", Color::Purple) };
  Component body{ render_body(app_state) }; 

  Component layout { Container::Vertical({
    header,
    body,
    footer
  })};

  return Renderer(layout, [=]{
    return vbox({
      header->Render(),
      body->Render(),
      footer->Render()                  
    }) | borderLight | color(theme::BORDER_COLOR) | bgcolor(theme::BODY_BG_COLOR);
  });
}


