#include "screens.h"
#include "../theme.h"
#include "../components/container.h"
#include "../components/input_field_component.h"
#include "../app_state.h"
#include "ui_constants.h"
#include <cctype>
#include <cstddef>
#include <ftxui/component/app.hpp>
#include <ftxui/component/component.hpp>
#include <ftxui/component/component_base.hpp>
#include <ftxui/component/component_options.hpp>
#include <ftxui/component/event.hpp>
#include <ftxui/dom/elements.hpp>
#include <ftxui/screen/color.hpp>
#include <ftxui/screen/terminal.hpp>
#include <functional>
#include <string_view>
#include <algorithm>
#include <vector>

using namespace ftxui;

namespace theme = ui::theme;
namespace state = ui::state;
namespace constants = ui::screens::constants;

namespace{

// levenshtein distance formula to determine how similar two strings are
// generated by Gemini
auto levenshtein(std::string_view s1, std::string_view s2) -> int{
    const size_t s1_length = s1.size();
    const size_t s2_length = s2.size();

    // Use a single vector to track distances (current row)
    std::vector<int> distances(s2_length + 1);
    std::iota(distances.begin(), distances.end(), 0); 

    for (size_t i = 1; i <= s1_length; ++i) {
        int upper_left = distances[0]; // The "diagonal" value
        distances[0] = static_cast<int>(i); // Update the first column

        for (size_t j = 1; j <= s2_length; ++j) {
            int prev_upper_left = upper_left;
            upper_left = distances[j]; // Save for the next iteration's diagonal

            if (s1[i - 1] == s2[j - 1]) {
                distances[j] = prev_upper_left; // Characters match, no cost
            } else {
                // Take the minimum of (Insertion, Deletion, Substitution) + 1
                distances[j] = 1 + std::min({distances[j], distances[j - 1], prev_upper_left});
            }
        }
    }
    return distances[s2_length];
}

void select_main_menu_from_search_menu(state::AppState& app_state)
{
  std::string_view target{ app_state.search.sites[static_cast<std::size_t>(app_state.search.curr_site_index)] };

  for (std::size_t i{}; i < app_state.main_vault.sites.size(); i++)
  {
    std::string_view curr_site{ app_state.main_vault.sites[i] };
    if (curr_site == target){
      app_state.main_vault.entry_selected = static_cast<int>(i);
      return;
    }
  }
}


auto render_body(state::AppState& app_state) -> Component
{
  using namespace ui::components;

  std::function<void()> on_input_change{[&]{
    std::sort(app_state.search.sites.begin(), app_state.search.sites.end(), [&](std::string_view first, std::string_view second) {
      auto score_a = 1.0 - (static_cast<double>(levenshtein(first, app_state.search.search_field)) / std::max(first.size(), app_state.search.search_field.size()));
      auto score_b = 1.0 - (static_cast<double>(levenshtein(second, app_state.search.search_field)) / std::max(second.size(), app_state.search.search_field.size()));

      return score_a > score_b;
    });
  }};

  Filter search_filter{filter_combiner(newline_input_filter, char_limit_input_filter(&app_state.search.search_field, constants::MAX_INPUT_CHARACTERS))};
  Component search_field{create_input_field(&app_state.search.search_field, "Search...", search_filter, !IS_PASSWORD_INPUT, on_input_change)};

  MenuOption option;

  option.on_enter = [&]{
    select_main_menu_from_search_menu(app_state);
    app_state.selected_screen = ui::state::SelectedScreen::MainVault;
  };

 auto menu{Menu(&app_state.search.sites, &app_state.search.curr_site_index, option) | color(theme::FONT_COLOR)};
  
  auto layout{ Container::Vertical({
    search_field,
    menu,
  })};
  
  return Renderer(layout, [=, &app_state]{
    return hbox({
      separatorEmpty() | xflex,

      vbox({
        separatorEmpty() | size(ftxui::HEIGHT, ftxui::EQUAL, 4),
        search_field->Render(),
        separatorEmpty(),

        menu->Render() | vscroll_indicator | frame | yflex | borderLight,

        separatorEmpty() | size(ftxui::HEIGHT, ftxui::EQUAL, 4),
      }) | flex | size(ftxui::WIDTH, EQUAL, constants::MAX_INPUT_WIDTH),
      separatorEmpty() | xflex
    }) | flex;
  });
}

  
}// unnamed namespace


auto ui::screens::render_search_screen(state::AppState& app_state) -> Component
{
  Component header { components::render_header("SEARCH") };
  Component footer{ components::render_footer("EDITING", Color::Purple) };
  Component body{ render_body(app_state) }; 

  Component layout { Container::Vertical({
    header,
    body,
    footer
  })};

  return Renderer(layout, [=]{
    return vbox({
      header->Render(),
      body->Render(),
      footer->Render()                  
    }) | borderLight | color(theme::BORDER_COLOR) | bgcolor(theme::BODY_BG_COLOR);
  });
}


